#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Validate commit message with commitlint
echo "📝 Validating commit message..."
npx --no-install commitlint --edit $1

echo "✅ Commit message is valid!"
