name: Publish Packages to npmjs

on:
  push:
    branches:
      - package-release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
      url: https://www.npmjs.com/~your-npm-username
    if: github.ref == 'refs/heads/package-release'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - name: Publish all packages
        run: |
          for dir in packages/*/; do
            cd "$dir"
            if [ -f package.json ]; then
              npm publish --access public || true
            fi
            cd -
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
