name: Publish Packages to npmjs
on:
  workflow_dispatch:
    inputs:
      confirm_publish:
        description: 'Check to confirm you want to publish to npmjs'
        required: true
        type: boolean
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm run build
      - name: Publish all packages
        if: ${{ github.event.inputs.confirm_publish == 'true' }}
        run: |
          for dir in packages/*/; do
            cd "$dir"
            if [ -f package.json ]; then
              npm publish --access public || true
            fi
            cd -
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
